### PR TITLE
Upgrade confluent version to 3.2

### PR DESCRIPTION
**Pull request by mtagle**

### CODE REVIEW

**Comment by C0urante** [comment]
Has anybody checked to see if the cherry-picking outlined in the README for Schema Registry is still necessary to build the connector? Might want to nix that section now if the bump to 3.2 takes care of it.

**Comment by criccomini** [comment]
LGTM! Go ahead and merge

**Comment by criccomini** [comment]
@C0urante good question... I don't think it is, but should double check. If not, @mtagle can you do a separate PR for that?

**Comment by mtagle** [comment]
@criccomini will do.

**Pull request merged**
