### PR TITLE
issues #169 and #201 : Added support to configure BigQuery partition

### PR DESCRIPTION
**Pull request by darshanmehta10**
This is a duplicate of #203 and #229 as I had issues with licence/cla and/or other commits

### CODE REVIEW

**Comment by skyzyx** [comment]
# [Codecov](https://codecov.io/gh/wepay/kafka-connect-bigquery/pull/244?src=pr&el=h1) Report
> Merging [#244](https://codecov.io/gh/wepay/kafka-connect-bigquery/pull/244?src=pr&el=desc) into [master](https://codecov.io/gh/wepay/kafka-connect-bigquery/commit/08f1a01b98d18a2ac25930cebf4e9aacd2d7e58e&el=desc) will **increase** coverage by `0.14%`.
> The diff coverage is `n/a`.


```diff
@@             Coverage Diff              @@
##             master     #244      +/-   ##
============================================
+ Coverage     68.89%   69.03%   +0.14%     
- Complexity      275      276       +1     
============================================
  Files            32       32              
  Lines          1469     1476       +7     
  Branches        154      155       +1     
============================================
+ Hits           1012     1019       +7     
  Misses          409      409              
  Partials         48       48              
```

**Comment by darshanmehta10** [comment]
@mtagle continuing our discussion from #229 this is the PR with only my commits. Could you please have a look.

**Comment by levzem** [comment]
@darshanmehta10 @mtagle 

not sure if I misunderstand the PR, so please correct me if I am.

The way I am looking at it is that we are just removing the `PartitionDecorator`. If we remove the `PartitionDecorator`, then BigQuery can use column based partitioning to partition the records, however, the BigQuery table needs to be preconfigured beforehand to specify which field in the record is the column to be partitioned on. What if the table is not created yet and `auto.create.tables = true`. Will column based partitioning still work and if so, how will BigQuery know which column to partition on?

**Comment by darshanmehta10** [comment]
@levzem Yes, BigQuery table needs to be configured beforehand in order to use this feature. There is an open request to add this support to this component, you can track it [here](https://github.com/wepay/kafka-connect-bigquery/issues/169).

**Comment by darshanmehta10** [comment]
@mtagle Does it look good to you now?

**Comment by mtagle** [comment]
Yup, looks good! thank you!

**Pull request merged**
