### PR TITLE
Support Java 11

### PR DESCRIPTION
**Pull request by ivanyu**
This commit upgrade Gradle used in the project to the latest available
version 5.5 to support Java 11.
It also switches from (now deprecated) FindBugs plugin in SpotBugs for
the same reason.
`gradle/wrapper` directory and `gradlew.{bat|sh}` are re-generated
automatically by Gradle.

### CODE REVIEW

**Comment by ivanyu** [comment]
Sorry, missed this issue with Javadoc, fixing it.

**Comment by ivanyu** [comment]
Would you consider merging this?

**Comment by mtagle** [comment]
Yes! I just want to verify that this will still continue to work with older versions of java?

**Comment by ivanyu** [comment]
@mtagle it will. It's checked on Travis.
Also, I found that `sourceCompatibility` hasn't been set correctly. I fixed this in a new commit and now it should always target compatibility with Java 8 despite the JDK version being used for building.

**Pull request merged**
